name: advices
description: Demonstrates how to use the agora_rtc_engine plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  http: ^0.13.3
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  firebase_auth: ^3.11.0
  cloud_firestore: ^3.1.12
  cloud_functions: ^3.3.9
  firebase_dynamic_links: ^4.3.9
  agora_rtc_engine: ^5.2.0
  table_calendar: ^3.0.5
  date_time_picker: "^2.1.0"
  time_picker_widget: ^1.0.0+10
  provider: ^6.0.2
  permission_handler: ^10.0.2
  path_provider: ^2.0.8
  multi_select_flutter: ^4.1.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  pointer_interceptor: ^0.9.3+2
  flutter_secure_storage: ^6.0.0
  google_sign_in: ^5.3.0
  flutter_facebook_auth: ^4.4.1+1
  twitter_login: ^4.0.1
  # get: ^4.6.5
  url_launcher: ^6.1.0
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  js: ^0.6.4
  flutter_dotenv: ^5.0.2
  timeago: ^3.3.0





dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  pigeon: ^4.2.0
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - .env
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - lib/assets/images/backgroundImage.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
