// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiAEEwDoeQx_Q1_Kj94RyxbVOJR02ifo',
    appId: '1:968596221490:web:2b4163af286075dc80962b',
    messagingSenderId: '968596221490',
    projectId: 'advices-prod',
    authDomain: 'advices-prod.firebaseapp.com',
    storageBucket: 'advices-prod.appspot.com',
    measurementId: 'G-3BJ9SPYJEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2YNLDG1iyhp7CvcIsahiY2pJAwCNdmNI',
    appId: '1:968596221490:android:bef2f61a12920d5780962b',
    messagingSenderId: '968596221490',
    projectId: 'advices-prod',
    storageBucket: 'advices-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jeGN8TewtAY27yKsiqvNME5eAruxqtw',
    appId: '1:968596221490:ios:bd57621e9b1971b680962b',
    messagingSenderId: '968596221490',
    projectId: 'advices-prod',
    storageBucket: 'advices-prod.appspot.com',
    iosClientId: '968596221490-4q2csh9d19bfvivv5l0c16qc3ck5tsk5.apps.googleusercontent.com',
    iosBundleId: 'io.advices.virtualOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jeGN8TewtAY27yKsiqvNME5eAruxqtw',
    appId: '1:968596221490:ios:bd57621e9b1971b680962b',
    messagingSenderId: '968596221490',
    projectId: 'advices-prod',
    storageBucket: 'advices-prod.appspot.com',
    iosClientId: '968596221490-4q2csh9d19bfvivv5l0c16qc3ck5tsk5.apps.googleusercontent.com',
    iosBundleId: 'io.advices.virtualOffice',
  );
}
