// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMiXYCdnUTqZItvme_QYds_TTNCLXGmac',
    appId: '1:793184649946:web:9551788cf7f51068cd9be3',
    messagingSenderId: '793184649946',
    projectId: 'advices-dev',
    authDomain: 'advices-dev.firebaseapp.com',
    storageBucket: 'advices-dev.appspot.com',
    measurementId: 'G-QPSYB5REK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQB46UzQC_tOe8kdMkt7FIA4SnQdOa44',
    appId: '1:793184649946:android:d270d7ce1f7b80e3cd9be3',
    messagingSenderId: '793184649946',
    projectId: 'advices-dev',
    storageBucket: 'advices-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVP_mV2EHY-QXzQfVbWGWw8qLZXySoymo',
    appId: '1:793184649946:ios:24fd3d8f1d398e20cd9be3',
    messagingSenderId: '793184649946',
    projectId: 'advices-dev',
    storageBucket: 'advices-dev.appspot.com',
    androidClientId: '793184649946-73809u4lilv8vllsl1i79f89550c7pti.apps.googleusercontent.com',
    iosClientId: '793184649946-f4v5k8rn5a63qf58v8u77759bou95ieg.apps.googleusercontent.com',
    iosBundleId: 'io.agora.agoraRtcEngineExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVP_mV2EHY-QXzQfVbWGWw8qLZXySoymo',
    appId: '1:793184649946:ios:24fd3d8f1d398e20cd9be3',
    messagingSenderId: '793184649946',
    projectId: 'advices-dev',
    storageBucket: 'advices-dev.appspot.com',
    androidClientId: '793184649946-73809u4lilv8vllsl1i79f89550c7pti.apps.googleusercontent.com',
    iosClientId: '793184649946-f4v5k8rn5a63qf58v8u77759bou95ieg.apps.googleusercontent.com',
    iosBundleId: 'io.agora.agoraRtcEngineExample',
  );
}
